import type { Metadata } from 'next';
import './globals.css';
import iranSans from '@/config/localFont';
import { ReactNode } from 'react';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  authModal,
}: Readonly<{
  children: ReactNode;
  authModal: ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${iranSans.className} ${iranSans.variable}`}>
        <main style={{ height: '3000px' }}>
          {authModal}
          {children}
          <div id="portal-root" />
        </main>
      </body>
    </html>
  );
}
