import type { Metadata } from 'next';
import './globals.css';
import iranSans from '@/config/localFont';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${iranSans.className} ${iranSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
